@jwt = yJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2ODQwMDQ1MTV9.eYXaUGw5lpfy4tbSfXMG6qv93ZeOevwQMuZCRZN6aOc

POST http://localhost:3000/sessions.json
Content-Type: application/json 

{
  "email": "Leah@test.com",
  "password": "password"
}

###

POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Crush",
  "email": "Crush@test.com",
  "password": "password",
  "password_confirmation": "password",
  "image_url": "image url"
}
###

POST http://localhost:3000/hikes.json
Content-Type: application/json

{
  "name": "Horsetooth Mountain Trail",
  "park_name": "Horsetooth Mountain Open Space",
  "distance": 8.9,
  "time": "4 hours 38 minutes",
  "image_url": "https://www.larimer.gov/sites/default/files/06_horsetooth_mountain_01_by_jeanie_sumrall-ajero.jpg",
  "route_type": "loop",
  "dog_friendly": true
}

###

GET http://localhost:3000/hikes.json

###

POST http://localhost:3000/reviews.json
Content-Type: application/json

{
  "hike_id": 9,
  "user_id": 3,
  "ranking": 5,
  "comments": "amazing",
  "image_url": "https://www.larimer.gov/sites/default/files/06_horsetooth_mountain_01_by_jeanie_sumrall-ajero.jpg",
  "time": "2 hours"
}